shell.run("clear")
paintutils.drawFilledBox(2, 2, 50, 7, colors.gray)
term.setCursorPos(3, 3)
term.setBackgroundColor(colors.black)
print('Home')
term.setBackgroundColor(colors.gray)
term.setCursorPos(22, 3)
term.setTextColor(colors.green)
print('Linux XP')
print("")
term.setCursorPos(7, 5)
print("Date & Time:", os.date())
term.setCursorPos(17, 6)
print("Welcome back user!")
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
print("")
print("")
term.setCursorPos(3, 9)
print("1.               runWebCon.lua")