shell.run("clear")

paintutils.drawFilledBox(2, 2, 50, 6, colors.gray)
term.setCursorPos(22, 3)
term.setTextColor(colors.green)
print('Linux XP')
print("")
term.setCursorPos(10, 5)
print("Welcome to the command prompt!")
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
print("")
print("")
term.setCursorPos(2, 8)